### ISSUE TITLE
How to cite 3D Forest 

### ISSUE THREAD

**Issue by LennarTLS** [VUKOZ-OEL/3DForest#37]
Hi guys,

thanks for developing and providing this great application!

I used 3D forest for ground classification, tree segmentation and some tree attribute calculations. 
I just want to know how I should cite your work.
Should I refer to this paper: Trochta, J., Krůček, M., Vrška, T., & Král, K. (2017). 3D Forest: An application for descriptions of three-dimensional forest structures using terrestrial LiDAR. PloS one, 12(5), e0176871. Or is there a more recent one?

Also, the contact form on 3dforest.eu does not seem to work at the moment. 

Cheers

**Comment by janekT** [comment]
Hi thanks for comment you can use mentioned paper as reference, since we do not have any other paper about it.  Comment from website was delivered but I was out of office..
